### ISSUE TITLE
nosteam configuration?

### ISSUE THREAD

**Issue by g-plopez** [cyrale/project-zomboid#10]
I have the question that if it can be placed in nosteam mode, I have bought the game but 1 friend wants to play with us and cannot enter because he tells him that he can only play on non-steam servers.
Any way to configure it like this? since I put the command in my game on steam as -nosteam but it won't let me enter.
I have it hosted on a VPS, where I already tried connecting as a steam user and it works perfect.

**Comment by cyrale** [comment]
I found something in server-files volume. A variable named Dzomboid.steam set to 1 by default in 3 files: start-server.sh, ProjectZomboid32.json and ProjectZomboid64.json. Maybe if you change any of these variables or set -nosteam next to them, it might work for you.

**Comment by g-plopez** [comment]
Thank you very much for your comments, I tried to make the change, I saved it in the 3 files, but every time I do the docker-compose up
It recreates all the data for me and does not save that configuration.

Docker-compose.yml
```
version: "3.0"

services:
    project-zomboid:
        image: cyrale/project-zomboid
        restart: unless-stopped
        environment:
            SERVER_NAME: "wuazholand"
            ADMIN_PASSWORD: "123"
            SERVER_PASSWORD: "3312"
            SERVER_NAME: "wuazholand"
            SERVER_PUBLIC_NAME: "wuazholand"
        ports:
            - "8766:8766/udp"
            - "8767:8767/udp"
            - "16261:16261/udp"
            - "16262-16272:16262-16272"
            - "27015:27015"
        volumes:
            - ./server-data:/server-data
            - ./server-files:/server-files
```

start-server.sh
```
...
LD_PRELOAD=/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libjsig.so \
java \
	-Dzomboid.steam=0 -Dzomboid.znetlog=1 \
	-Djava.library.path="${INSTDIR}/natives:${INSTDIR}/linux64" \
	-Xms2048m \
	-Xmx2048m \
	-XX:-UseSplitVerifier \
	-cp "${JARPATH}" \
	zombie.network.GameServer \
	"$@"

exit 0
```

ProjectZomboid32 and 64
```
...
	"vmArgs": [
		"-Xms2048m",
		"-Xmx2048m",
		"-Dzomboid.steam=0",
		"-Dzomboid.znetlog=1",
		"-Djava.library.path=linux64/:natives/",
		"-XX:-UseSplitVerifier",
		"-Djava.security.egd=file:/dev/urandom",
		"-XX:+UseConcMarkSweepGC",
		"-XX:-OmitStackTraceInFastThrow"
	]
```
It would be too much to ask that this configuration could be added to an environment?
