### ISSUE TITLE
Problems starting docker compose in daemon

### ISSUE THREAD

**Issue by nicolasegp** [cyrale/project-zomboid#11]
If use `docker-compose up -d` I get the following error

```
1622489323661 RCON: listening on port 27015
1622489323947 Missing texture: media/textures/weather/fogwhite.png
1622489324063 znet: OnPolicyResponse
1622489324064 znet: Zomboid Server is VAC Secure
./start-server.sh: line 21:  3161 Killed                  LD_PRELOAD="${LD_PRELOAD}:${JSIG}" ./ProjectZomboid64 "$@"
```

But if use `docker-comopse up` the server starts normally

---

```
Docker version 20.10.6, build 370c289
docker-compose version 1.25.0, build unknown
```

---

```yml
version: "3.7"
services:
    project-zomboid:
        image: ghcr.io/cyrale/project-zomboid
        restart: unless-stopped
        environment:
            SERVER_NAME: "MyServer"
            SERVER_PASSWORD: "*****"
            ADMIN_PASSWORD: "*****"
        ports:
            - "8766:8766/udp"
            - "8767:8767/udp"
            - "16261:16261/udp"
            - "16262-16272:16262-16272"
            - "27015:27015"
        volumes:
            - ./server-data:/server-data

```
