### ISSUE TITLE
Server fails to start with default configuration (znet: ERROR: couldn’t parse IP)

### ISSUE THREAD

**Issue by FatalMerlin** [cyrale/project-zomboid#6]
**Describe the bug**
Server fails to start with default configuration (znet: ERROR: couldn’t parse IP).

The default LGSM configuration provides the IP as "0.0.0.0", which the server does not parse / allow.
The server must be configured to use the docker IP address.

**To Reproduce**
1. Create a new server as described in the README
2. Wait for the server to fail during startup

**Expected behavior**
The image should read the container IP address and set the server IP accordingly.

**Additional context**
Reference: [Linux GSM Forum](https://forum.linuxgsm.com/t/i-cant-start-my-pz-server/152)

**Workaround**
The problem can be fixed using Docker Compose and changing the compose file to give the container a static IP address and add it to the LGSM instance config:
```yaml
version: "3.0"

services:
    project-zomboid:
        image: cyrale/project-zomboid
        restart: unless-stopped
        environment:
            SERVER_NAME: "MyServer"
            SERVER_PASSWORD: "Sh00tZ0mb13s"
            ADMIN_PASSWORD: "l3tm31n"
            PLAYER_PORTS: "10"
            # SERVER_BRANCH: "iwillbackupmysave"
            # Insert server IP into LGSM instance config
            LGSM_SERVER_CONFIG: |
              ip="172.20.128.2"
        ports:
            - "8766:8766/udp"
            - "8767:8767/udp"
            - "16261:16261/udp"
            - "16262-16272:16262-16272"
            - "27015:27015"
        volumes:
            - ./server-data:/server-data
            - ./server-files:/server-files
        # Give the container a static IP address
        networks:
            static-network:
              ipv4_address: 172.20.128.2
        restart: always

# Create a network to apply a conflict free static IP
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
```
